# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -std=c++17 -Wall -Wextra -pedantic

# Linker flags (to link with libcurl)
LDFLAGS = -lcurl -pthread -lcrypto

# Source files
SRCS = easy_math.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Executable name
EXEC = easy_math

# Default target
all: $(EXEC)

# Link object files to create executable
$(EXEC): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# Compile source files to object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean up build files
clean:
	rm -f $(OBJS) $(EXEC)
